title: FocusNFe Java Client
description: REST Client - FocusNFe Brazilian fiscal Issuer NF-e NFC-e API.
google_analytics: 
show_downloads: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
